backend:
  name: git-gateway
  branch: main

media_folder: static/uploads
public_folder: /uploads


collections:
  - name: "posts"
    label: "뉴스 게시글"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "내용", name: "body", widget: "markdown" }
      - { label: "이미지", name: "image", widget: "image" }
