backend:
  name: git-gateway
  branch: main # GitHub 저장소의 배포 브랜치

media_folder: static/uploads # 이미지가 저장되는 실제 디렉토리
public_folder: /uploads       # 브라우저에서 참조하는 경로

collections:
  - name: blog
    label: Blog
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Featured Image, widget: image }
